export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const ADMIN_SIGNUP = 'ADMIN_SIGNUP';
export const ADMIN_SIGNUP_SUCCESS = 'ADMIN_SIGNUP_SUCCESS';
export const ADMIN_SIGNUP_ERROR = 'ADMIN_SIGNUP_ERROR';
export const ADMIN_SIGNIN = 'ADMIN_SIGNIN';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGIN_SUCCESS';
export const ADMIN_SIGNIN_ERROR = 'ADMIN_SIGNIN_ERROR';
